/*
  Warnings:

  - The values [RESIDUAL_WASTE,GLASS_WASTE,GLASS_AND_METAL,METAL_WASTE,HOUSEHOLD_WASTE,COMMERCIAL_WASTE,HAZARDOUS_WASTE,CONSTRUCTION_AND_DEMOLITION_WASTE,RECYCLING,SPECIAL_WASTE,ORGANIC_WASTE,ELECTRONIC_WASTE] on the enum `AgreementType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AgreementType_new" AS ENUM ('RESTAVFALL', 'GLASSAVFALL', 'GLASSOGMETALL', 'METALLAVFALL', 'HUSHOLDNINGSAVFALL', 'NAERINGSAVFALL', 'FARLIGAVFALL', 'BYGGOGANLEGGSAVFALL', 'GJENVINNING', 'SPESIALAVFALL', 'ORGANISKAVFALL', 'ELEKTRONISKAVFALL');
ALTER TABLE "Agreement" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "Agreement" ALTER COLUMN "type" TYPE "AgreementType_new" USING ("type"::text::"AgreementType_new");
ALTER TYPE "AgreementType" RENAME TO "AgreementType_old";
ALTER TYPE "AgreementType_new" RENAME TO "AgreementType";
DROP TYPE "AgreementType_old";
ALTER TABLE "Agreement" ALTER COLUMN "type" SET DEFAULT 'RESTAVFALL';
COMMIT;

-- AlterTable
ALTER TABLE "Agreement" ALTER COLUMN "type" SET DEFAULT 'RESTAVFALL';
