@startuml CRS Level 1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include <office/users/users.puml>
!include <office/users/mobile_user.puml>
!include <office/users/administrator.puml>

LAYOUT_WITH_LEGEND()

title Context Diagram For Container Rental System

Person(user, "Kontoransatt", "En ansatt i en bedrift som leier ut containere")

System(CRS_Web_Client, "Container Rental System", "System for håndtering av avfallskontainer")
System_Ext(mail_service, "Gmail", "Email provider. Brukes til å sende e-poster i forbindelse med verifisering av konto og invitasjon")
System_Ext(supabase, "Supabase \n Backend as a Service (BaaS)", "Brukes for database, authentication, fil lagring, edge functions etc.")

Rel_D(user, CRS_Web_Client, "CRUD kunder, biler, sjåfører, container, oppdrag og avtaler")
Rel_R(CRS_Web_Client, mail_service, "Sender e-poster v.h.a.")
BiRel_D(CRS_Web_Client, supabase, "Data")
Rel_U(mail_service, user, "Sender e-poster til")

@enduml

